# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  platform :ios, '11.0'
  use_frameworks!

  pod 'RXCDiffArray', :path => '../'
  pod 'RXCDiffArray/DifferenceKit', :path => '../'
  pod 'DifferenceKit/UIKitExtension'
  
end
